package com.jarvis.controller.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2196F3)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBDEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_theme_light_secondary = Color(0xFF03DAC6)
val md_theme_light_onSecondary = Color(0xFF000000)
val md_theme_light_secondaryContainer = Color(0xFFB2EBF2)
val md_theme_light_onSecondaryContainer = Color(0xFF00695C)
val md_theme_light_tertiary = Color(0xFFFF6B9D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFB3D9)
val md_theme_light_onTertiaryContainer = Color(0xFF88184D)
val md_theme_light_error = Color(0xFFCF6679)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_outline = Color(0xFF79747E)

val md_theme_dark_primary = Color(0xFF64B5F6)
val md_theme_dark_onPrimary = Color(0xFF0D47A1)
val md_theme_dark_primaryContainer = Color(0xFF1565C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBDEFB)
val md_theme_dark_secondary = Color(0xFF4DD0E1)
val md_theme_dark_onSecondary = Color(0xFF004D4D)
val md_theme_dark_secondaryContainer = Color(0xFF006064)
val md_theme_dark_onSecondaryContainer = Color(0xFFB2EBF2)
val md_theme_dark_tertiary = Color(0xFFFF80AB)
val md_theme_dark_onTertiary = Color(0xFF660033)
val md_theme_dark_tertiaryContainer = Color(0xFF88184D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFB3D9)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1F1F1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_outline = Color(0xFF998FA3)
